name: CI/CD Flask Render

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    # - run: pip install -r requirements.txt

    - name: Make Venv
      run: |
        python3 -m venv .venv

    - name: Go to Venv
      run: |
        . .venv/bin/activate

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: List
      run: |
        ls flaskr

    - name: Make Test
      run: |
        pytest


