name: CI/CD Flask Render

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "."
        target: "test-a.txt"

    - name: Make Test
      run: |
        pytest


