name: CI/CD Flask Render

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=." >> $GITHUB_ENV

    - name: Create Sqlite Database
      run: |
        mkdir -p instance
        flask --app flaskr init-db

    - name: Make boot sh executable
      run: |
        chmod +x boot.sh

    - name: Make Test
      run: |
        pytest

    - name: Deploy
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$deploy_url"


